import type { ExplanationMap } from 'theme-base';

/**
 * Explicações curtas (1 frase) das palavras-alvo do tema Copa.
 * Exibidas no modal de fim de jogo abaixo da palavra revelada.
 *
 * Quando o jogador joga uma palavra que não conhece (ex: TUNIS), a
 * explicação ensina o significado — UX "joguei pra descobrir, agora
 * sei o que é".
 *
 * Palavras sem entrada aqui caem num fallback genérico via
 * `getExplanation()` (wordle-app/src/i18n).
 */
export const copaExplanationsPt: ExplanationMap = {
  ABUJA: 'Capital da Nigéria.',
  ALABA: 'David Alaba, zagueiro austríaco, capitão da Áustria.',
  APITO: 'Som usado pelo árbitro para sinalizar o jogo.',
  ARENA: 'Sinônimo de estádio de futebol.',
  ARGEL: 'Capital da Argélia.',
  BAGDA: 'Capital do Iraque (Bagdá).',
  BANKS: 'Gordon Banks, goleiro inglês campeão da Copa de 1966.',
  BERNA: 'Capital da Suíça.',
  BLANC: 'Laurent Blanc, zagueiro francês campeão da Copa de 1998.',
  BOBAN: 'Zvonimir Boban, meia croata da Copa de 1998.',
  BOLAS: 'Equipamento principal do futebol.',
  CAIRO: 'Capital do Egito.',
  CAMPO: 'Local onde se joga o futebol.',
  CATAR: 'Seleção do Catar, anfitriã da Copa de 2022.',
  CESAR: 'Júlio César, goleiro do Brasil nas Copas de 2010 e 2014.',
  CHILE: 'Seleção do Chile, sede da Copa de 1962.',
  CHUTE: 'Ação de bater na bola com o pé.',
  COBRA: 'Verbo "cobrar" — executar pênalti ou falta.',
  COMAN: 'Kingsley Coman, ponta francês.',
  COPAS: 'Plural de copa — torneios.',
  CRACK: 'Jogador excepcional (gíria).',
  DAKAR: 'Capital do Senegal.',
  DUNGA: 'Carlos Dunga, capitão do tetra na Copa de 1994.',
  DZEKO: 'Edin Džeko, atacante bósnio.',
  EGITO: 'Seleção do Egito (CAF).',
  ELANO: 'Elano Blumer, meia da Seleção Brasileira na Copa de 2010.',
  FALTA: 'Infração cometida durante o jogo.',
  FAVRE: 'Lucien Favre, técnico suíço.',
  FENOM: '"Fenômeno", apelido de Ronaldo Nazário.',
  FERAS: 'Gíria para jogadores excepcionais.',
  FESTA: 'Comemoração de gol ou título.',
  FINAL: 'Última partida do torneio.',
  GOTZE: 'Mario Götze, autor do gol decisivo da Copa de 2014.',
  GRITO: 'Berro de gol pela torcida.',
  GRUPO: 'Fase de grupos da Copa (A, B, C…).',
  HENRY: 'Thierry Henry, atacante francês campeão da Copa de 1998.',
  HINOS: 'Cantados pelas seleções antes das partidas.',
  JAPAO: 'Seleção do Japão, presença constante nas Copas.',
  JOGAR: 'Praticar a partida.',
  JOGOS: 'Partidas, encontros, confrontos.',
  KEANE: 'Roy Keane, capitão histórico da Irlanda.',
  KLOPP: 'Jürgen Klopp, técnico alemão.',
  KLOSE: 'Miroslav Klose, maior artilheiro da história das Copas (16 gols).',
  KROOS: 'Toni Kroos, meia alemão campeão da Copa de 2014.',
  LANCE: 'Jogada específica dentro da partida.',
  LIPPI: 'Marcello Lippi, técnico italiano campeão da Copa de 2006.',
  LUCAS: 'Lucas Paquetá, meia da Seleção Brasileira atual.',
  LUCIO: 'Lúcio, zagueiro do penta brasileiro na Copa de 2002.',
  MADRI: 'Capital da Espanha.',
  MESSI: 'Lionel Messi, capitão argentino campeão da Copa de 2022.',
  MIAMI: 'Cidade-sede da Copa 2026 (Estados Unidos).',
  NEUER: 'Manuel Neuer, goleiro alemão campeão da Copa de 2014.',
  PARIS: 'Capital da França.',
  PASSE: 'Ação de passar a bola a outro jogador.',
  PEGAR: 'Goleiro defender a bola.',
  PENAL: 'Tiro de penalidade máxima.',
  PERDE: 'Forma do verbo "perder" — sair derrotado.',
  PETIT: 'Emmanuel Petit, meia francês campeão da Copa de 1998.',
  PIRLO: 'Andrea Pirlo, meia italiano campeão da Copa de 2006.',
  PISAR: 'Pisar no gramado — entrar em campo.',
  PODIO: 'Os três primeiros colocados em torneio.',
  PRAGA: 'Capital da Tchéquia.',
  PULAR: 'Comemorar pulando.',
  QUITO: 'Capital do Equador.',
  RABAT: 'Capital do Marrocos.',
  RIADE: 'Capital da Arábia Saudita (Riade).',
  ROSSI: 'Paolo Rossi, artilheiro e campeão da Copa de 1982 pela Itália.',
  SALAH: 'Mohamed Salah, atacante egípcio.',
  SEMIS: 'Semifinais — penúltima fase do torneio.',
  SUICA: 'Seleção da Suíça.',
  SUKER: 'Davor Šuker, artilheiro da Copa de 1998 pela Croácia.',
  TACAS: 'Troféus em formato de taça.',
  TEERA: 'Capital do Irã (Teerã).',
  TEVEZ: 'Carlos Tevez, atacante argentino.',
  TIMES: 'Equipes que disputam o torneio.',
  TOTTI: 'Francesco Totti, meia italiano campeão da Copa de 2006.',
  TRAVE: 'Estrutura vertical do gol.',
  TUNIS: 'Capital da Tunísia.',
  VARDY: 'Jamie Vardy, atacante inglês.',
  VENCE: 'Forma do verbo "vencer" — sair vitorioso.',
  VIDAL: 'Arturo Vidal, meia chileno.',
  VIENA: 'Capital da Áustria.',
  VILLA: 'David Villa, artilheiro espanhol campeão da Copa de 2010.',
};

export const copaExplanationsEn: ExplanationMap = {
  ACCRA: 'Capital of Ghana.',
  ALABA: 'David Alaba, Austrian defender.',
  ARENA: 'A sports stadium.',
  BALLS: 'Plural of soccer ball.',
  BANKS: 'Gordon Banks, English goalkeeper, 1966 World Cup champion.',
  BLANC: 'Laurent Blanc, French defender, 1998 World Cup champion.',
  BOOTS: 'Football boots / cleats.',
  CAIRO: 'Capital of Egypt.',
  CARDS: 'Yellow or red cards from the referee.',
  CHAMP: 'A champion.',
  CHANT: 'Songs sung by fans in the stadium.',
  CHILE: 'National team of Chile; host of the 1962 World Cup.',
  COMAN: 'Kingsley Coman, French winger.',
  CROSS: 'A cross pass into the box.',
  CROWD: 'The fans in the stadium.',
  CROWN: 'Symbol of being a champion.',
  DAKAR: 'Capital of Senegal.',
  DERBY: 'A high-rivalry match.',
  DRAWS: 'Tied results.',
  DUNGA: 'Carlos Dunga, Brazilian captain, 1994 World Cup winner.',
  DZEKO: 'Edin Džeko, Bosnian striker.',
  EGYPT: 'National team of Egypt.',
  FAVRE: 'Lucien Favre, Swiss coach.',
  FIELD: 'The football field.',
  FINAL: 'The final match of the tournament.',
  FLAGS: 'National flags carried by fans.',
  GHANA: 'National team of Ghana.',
  GLOVE: 'Goalkeeper glove.',
  GOALS: 'Scored points in football.',
  GOTZE: 'Mario Götze, scored Germany’s 2014 World Cup-winning goal.',
  GROUP: 'Group stage of the World Cup.',
  HEADS: 'Header — playing the ball with the head.',
  HENRY: 'Thierry Henry, French striker, 1998 World Cup champion.',
  ITALY: 'National team of Italy, four-time World Cup champion.',
  JAPAN: 'National team of Japan.',
  KEANE: 'Roy Keane, Irish captain and midfielder.',
  KICKS: 'Kicks of the ball.',
  KLOPP: 'Jürgen Klopp, German coach.',
  KLOSE: 'Miroslav Klose, top scorer in World Cup history (16 goals).',
  KROOS: 'Toni Kroos, German midfielder, 2014 World Cup champion.',
  LIPPI: 'Marcello Lippi, Italian coach, 2006 World Cup champion.',
  LUCIO: 'Lúcio, Brazilian defender, 2002 World Cup champion.',
  MATCH: 'A football match.',
  MEDAL: 'Awarded to winners.',
  MESSI: 'Lionel Messi, Argentine captain, 2022 World Cup champion.',
  MIAMI: 'Host city of the 2026 World Cup (USA).',
  NEUER: 'Manuel Neuer, German goalkeeper, 2014 World Cup champion.',
  PARIS: 'Capital of France.',
  PIRLO: 'Andrea Pirlo, Italian midfielder, 2006 World Cup champion.',
  PITCH: 'The football field surface.',
  POSTS: 'The goalposts.',
  PRIZE: 'A reward for winning.',
  QATAR: '2022 World Cup host.',
  RABAT: 'Capital of Morocco.',
  RIVAL: 'A rival team or player.',
  ROSSI: 'Paolo Rossi, top scorer of the 1982 World Cup for Italy.',
  ROUND: 'A round of the tournament.',
  SALAH: 'Mohamed Salah, Egyptian striker.',
  SAVES: 'A goalkeeper’s saves.',
  SCORE: 'The match score.',
  SEOUL: 'Capital of South Korea, co-host of the 2002 World Cup.',
  SHIRT: 'Football jersey.',
  SHOOT: 'Take a shot at goal.',
  SHOTS: 'Shots taken at goal.',
  SPAIN: 'National team of Spain, 2010 World Cup champion.',
  SUKER: 'Davor Šuker, top scorer of the 1998 World Cup for Croatia.',
  TEAMS: 'The football teams.',
  TITLE: 'A championship title.',
  TOKYO: 'Capital of Japan.',
  TOTTI: 'Francesco Totti, Italian midfielder, 2006 World Cup champion.',
  VARDY: 'Jamie Vardy, English striker.',
  VIDAL: 'Arturo Vidal, Chilean midfielder.',
  VILLA: 'David Villa, Spanish top scorer, 2010 World Cup champion.',
  WALES: 'National team of Wales.',
  WINGS: 'Wide positions on the pitch.',
  WORLD: 'The World Cup tournament.',
};
