/**
 * Downloads PT and EN wordlists from public sources, filters to 5-letter
 * normalized words (uppercase, no diacritics, A-Z only), dedupes, and writes
 * TS source files into ../src/.
 *
 * Run: `npm run download-wordlists --workspace=theme-base`
 *
 * Re-run when forking theme-base to a new theme so the validation pool stays
 * comprehensive. The generated files are committed (no fetch at runtime).
 */
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const SRC_DIR = join(__dirname, '..', 'src');

const DIACRITICS = /[̀-ͯ]/g;
function normalize(s: string): string {
  return s.normalize('NFD').replace(DIACRITICS, '').toUpperCase();
}

interface Source {
  name: string;
  urls: string[];
  license: string;
}

const SOURCES: Record<'pt' | 'en', Source> = {
  pt: {
    name: 'Portuguese',
    urls: [
      // ~318k Brazilian Portuguese words, MIT-style permissive
      'https://raw.githubusercontent.com/pythonprobr/palavras/master/palavras.txt',
      // Fallback: smaller curated set
      'https://raw.githubusercontent.com/fserb/pt-br/master/dicio',
    ],
    license: 'Public domain / permissive (pythonprobr/palavras)',
  },
  en: {
    name: 'English',
    urls: [
      // ~370k English words, MIT
      'https://raw.githubusercontent.com/dwyl/english-words/master/words_alpha.txt',
    ],
    license: 'MIT (dwyl/english-words)',
  },
};

async function fetchFirstAvailable(urls: readonly string[]): Promise<string> {
  let lastErr: unknown;
  for (const url of urls) {
    try {
      console.log(`  trying ${url}`);
      const r = await fetch(url, { signal: AbortSignal.timeout(120_000) });
      if (!r.ok) throw new Error(`HTTP ${r.status}`);
      const text = await r.text();
      console.log(`  ok (${(text.length / 1024).toFixed(1)} KB)`);
      return text;
    } catch (e) {
      console.log(`  failed: ${(e as Error).message}`);
      lastErr = e;
    }
  }
  throw new Error(`All sources failed. Last error: ${String(lastErr)}`);
}

function extractFiveLetter(text: string): string[] {
  const seen = new Set<string>();
  for (const raw of text.split(/\r?\n/)) {
    const w = normalize(raw.trim());
    if (w.length === 5 && /^[A-Z]+$/.test(w)) {
      seen.add(w);
    }
  }
  return [...seen].sort();
}

interface GenerateInput {
  locale: 'pt' | 'en';
  exportName: string;
  outFileName: string;
}

async function generate({ locale, exportName, outFileName }: GenerateInput) {
  const source = SOURCES[locale];
  console.log(`\n=== ${source.name} ===`);
  const text = await fetchFirstAvailable(source.urls);
  const words = extractFiveLetter(text);
  console.log(`  ${words.length} unique 5-letter words after normalize`);

  const header = `/**
 * Auto-generated by scripts/download-wordlists.ts from public sources.
 * License: ${source.license}.
 * DO NOT edit by hand — regenerate via 'npm run download-wordlists --workspace=theme-base'.
 *
 * ${words.length} 5-letter words, normalized (uppercase A-Z, no diacritics).
 */
`;
  const body =
    `export const ${exportName}: readonly string[] = [\n` +
    words.map((w) => `  '${w}',`).join('\n') +
    `\n];\n`;

  const outPath = join(SRC_DIR, outFileName);
  writeFileSync(outPath, header + body, 'utf-8');
  console.log(`  wrote ${outPath}`);
}

async function main() {
  await generate({
    locale: 'pt',
    exportName: 'wordsValidPt',
    outFileName: 'words.valid.pt.ts',
  });
  await generate({
    locale: 'en',
    exportName: 'wordsValidEn',
    outFileName: 'words.valid.en.ts',
  });
  console.log('\nDone.');
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
